# .goreleaser.yml
builds:
  # You can have multiple builds defined as a yaml list
  -
    id: yealink-click2dial
    binary: yealink-click2dial
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
archives:
  -
    builds:
      - default
    id: yealink-click2dial
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      amd64: win64
      386: win32
      darwin: macos
      linux: linux
