on: push
name: Build Release
jobs:
  release-linux-386:
    name: release linux/386
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: compile and release
      uses: ngs/go-release.action@v1.0.1
      env:
        CMD_PATH: -o yealink-click2dial
        GOARCH: "386"
        GOOS: linux
        EXTRA_FILES: "LICENSE"
